cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.instagram.com/david.snt0s/


file:
  upload-dir: /Users/David/Documents/Curso-SpringBoot-master/Projeto-Spring/arquivos

spring:
  application:
    name: Projeto-Spring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_spring?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB
springdoc:
  enable-hateoas: false
  paths-to-match: /books/**, /person/**
  swagger-ui:
    use-root-path: true
